webtalk_init -webtalk_dir C:/Users/Camil/OneDrive/Documentos/Laboratorios/Labs digitales/Sumador_BCD_/Sumador_BCD_.sim/sim_1/behav/xsim/xsim.dir/Sumador_BCD_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Oct  3 20:34:59 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f0db9f2e-ff74-4818-994a-7d2daffad059" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "1f0677ce0149417c839796afd0613fc0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-1035G4 CPU @ 1.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1498 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "6001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.11_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5868_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2423467237 -regid "" -xml C:/Users/Camil/OneDrive/Documentos/Laboratorios/Labs digitales/Sumador_BCD_/Sumador_BCD_.sim/sim_1/behav/xsim/xsim.dir/Sumador_BCD_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Camil/OneDrive/Documentos/Laboratorios/Labs digitales/Sumador_BCD_/Sumador_BCD_.sim/sim_1/behav/xsim/xsim.dir/Sumador_BCD_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Camil/OneDrive/Documentos/Laboratorios/Labs digitales/Sumador_BCD_/Sumador_BCD_.sim/sim_1/behav/xsim/xsim.dir/Sumador_BCD_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
